// Lesson content for Learning mode. Each lesson is data: a starting design (a validated preset
// with the lesson's own variables reset), the few controls the learner may change, the metrics
// to watch, "show the math" panels and a list of steps. A task step completes when its check(c,
// s) returns true for the lesson's live config `c` and computed scenario `s`.
import { DEFAULT_CONFIG, applyPresetConfig } from '../state/config.js';
import { USE_CASE_PRESETS } from '../data/presets.js';
import { PLATFORM_SYSTEMS } from '../data/platforms.js';
import { GPU_PRICING } from '../data/pricing.js';

const sec = (v) => (v < 1 ? `${Math.round(v * 1000)} ms` : `${v.toFixed(2)} s`);
const usd = (v) => `$${Math.round(v).toLocaleString()}`;
const gb = (v, d = 1) => `${Number(v).toLocaleString(undefined, { minimumFractionDigits: d, maximumFractionDigits: d })} GB`;

/** A preset with everything outside the lesson switched off, so only the lesson's variables move. */
function lessonBase(presetId, overrides) {
  const preset = USE_CASE_PRESETS.find(p => p.id === presetId);
  return {
    ...applyPresetConfig(DEFAULT_CONFIG, preset.config),
    sizingInputMode: 'concurrency',
    latencyTargetsEnabled: false,
    enableSpeculativeDecoding: false,
    requestMixEnabled: false,
    reasoningTokensPerOutputToken: 0,
    enableKvOffload: false,
    prefixCacheRatio: 0,
    enableRag: false,
    enableGuardrails: false,
    enableIngress: false,
    enableHaDr: false,
    enableMlops: false,
    enableMig: false,
    ...overrides,
  };
}

// Metrics a lesson can show. value(s, c) returns a number; format turns it into text.
export const METRICS = {
  weightsTotal: { label: 'Model weights', value: (s) => s.memory.weightTotalGb, format: (v) => gb(v) },
  usablePerGpu: { label: 'Usable memory per GPU', value: (s) => s.memory.usableGpuCapacityGb, format: (v) => gb(v) },
  gpus: { label: 'GPUs needed', value: (s) => s.results.totalGpus, format: (v) => v.toLocaleString() },
  sharding: { label: 'Layout', value: (s) => s.tp * 1e6 + s.pp * 1e3 + s.dp, format: (_v, s) => `TP=${s.tp}${s.pp > 1 ? ` × PP=${s.pp}` : ''} × DP=${s.dp}` },
  usedPerGpu: { label: 'Memory used per GPU', value: (s) => s.memory.perGpuTotalUsedGb, format: (v, s) => `${gb(v)} of ${s.gpu.vramGb} GB` },
  kvPerToken: { label: 'KV cache per token', value: (s) => s.memory.bytesPerTokenSeq, format: (v) => `${(v / 1e6).toFixed(2)} MB` },
  kvPerStream: { label: 'KV cache per stream', value: (s, c) => (s.memory.bytesPerTokenSeq * c.contextLength) / 1e9, format: (v) => gb(v) },
  kvAllStreams: { label: 'KV cache, all streams', value: (s, c) => (s.memory.bytesPerTokenSeq * c.contextLength * c.concurrency) / 1e9, format: (v) => gb(v) },
  weightsPerGpu: { label: 'Weights per GPU', value: (s) => s.memory.perGpuWeightsGb, format: (v) => gb(v) },
  nodes: { label: 'Servers (nodes)', value: (s) => s.results.nodes, format: (v) => v.toLocaleString() },
  ttft: { label: 'Time to first token', value: (s) => s.throughput.ttftSec, format: (v) => sec(v) },
  tpot: { label: 'Time per output token', value: (s) => Number(s.throughput.tpotMs), format: (v) => `${v.toFixed(1)} ms` },
  tokPerStream: { label: 'Speed per user', value: (s) => 1000 / Number(s.throughput.tpotMs), format: (v) => `${Math.round(v)} tokens/s` },
  clusterTps: { label: 'Total output throughput', value: (s) => s.throughput.batchThroughputTps, format: (v) => `${Math.round(v).toLocaleString()} tokens/s` },
  rps: { label: 'Peak requests per second', value: (s) => s.traffic.requestsPerSec, format: (v) => v.toFixed(2) },
  serviceTime: { label: 'Time per request', value: (s) => s.traffic.serviceTimeSec, format: (v) => sec(v) },
  inFlight: { label: 'Requests to hold at once', value: (s) => s.traffic.concurrency, format: (v) => v.toLocaleString() },
  p99Ttft: { label: 'P99 time to first token', value: (s) => s.sla.ttftP99Sec, format: (v) => sec(v) },
  leaf: { label: 'Leaf switches', value: (s) => s.network.leafSwitches, format: (v) => v.toLocaleString() },
  spine: { label: 'Spine switches', value: (s) => s.network.spineSwitches, format: (v) => v.toLocaleString() },
  transceivers: { label: 'Optical transceivers', value: (s) => s.network.transceivers, format: (v) => v.toLocaleString() },
  bisection: { label: 'Bisection bandwidth', value: (s) => s.network.effectiveBisectionTbps, format: (v) => `${v.toFixed(1)} Tbps` },
  itPower: { label: 'IT power', value: (s) => s.facility.totalItPowerKw, format: (v) => `${v.toFixed(1)} kW` },
  facilityPower: { label: 'Facility power (IT × PUE)', value: (s) => s.facility.totalFacilityPowerKw, format: (v) => `${v.toFixed(1)} kW` },
  perRack: { label: 'Servers per rack', value: (s) => s.facility.perRack, format: (v) => v.toLocaleString() },
  racks: { label: 'Racks', value: (s) => s.facility.totalRacks, format: (v) => v.toLocaleString() },
  energy: { label: 'Energy per year', value: (s) => s.energy.annualMwh, format: (v) => `${Math.round(v).toLocaleString()} MWh` },
  powerCost: { label: 'Power cost per year', value: (s) => s.cost.annualPowerCostUsd, format: (v) => usd(v) },
  trainingState: { label: 'Training state (all GPUs)', value: (s) => s.memory.weightTotalGb + (s.memory.gradientTotalGb || 0) + (s.memory.optimizerTotalGb || 0), format: (v) => gb(v, 0) },
  computeDays: { label: 'Compute time', value: (s) => s.trainingTime.computeDays, format: (v) => `${v.toFixed(1)} days` },
  wallDays: { label: 'Wall-clock time', value: (s) => s.trainingTime.wallClockDays, format: (v) => `${v.toFixed(1)} days` },
  goodput: { label: 'Goodput', value: (s) => s.trainingTime.goodputPct, format: (v) => `${v.toFixed(1)}%` },
  jobMtbf: { label: 'Time between failures (job)', value: (s) => s.trainingTime.jobMtbfHours, format: (v) => `${Math.round(v).toLocaleString()} h` },
  capex: { label: 'Capex', value: (s) => s.cost.totalCapexUsd, format: (v) => usd(v) },
  opex: { label: 'Opex per year', value: (s) => s.cost.annualOpexUsd, format: (v) => usd(v) },
  tco: { label: 'Total cost of ownership', value: (s) => s.cost.tcoUsd, format: (v, s) => `${usd(v)} (${s.cost.tcoYears} yr)` },
  usdPerGpuHour: { label: 'Cost per GPU-hour', value: (s) => s.cost.effectiveUsdPerGpuHour, format: (v) => `$${v.toFixed(2)}` },
  costPer1M: { label: 'Cost per 1M output tokens', value: (s) => s.tokenEconomics.costPer1MOutputTokensUsd, format: (v) => `$${v.toFixed(2)}` },
  reservedCloud: { label: 'Same GPUs, reserved cloud', value: (s) => s.rentVsBuy.options.find(o => o.id === 'reserved').usd, format: (v) => usd(v) },
};

// Controls a lesson can expose, bound to config fields shared with Advanced mode.
export const CONTROLS = {
  selectedModelId: {
    label: 'Model',
    options: [
      { value: 'llama3-8b', label: 'Llama 3.1 8B' },
      { value: 'llama33-70b', label: 'Llama 3.3 70B' },
      { value: 'llama3-405b', label: 'Llama 3.1 405B' },
    ],
  },
  selectedPrecisionId: {
    label: 'Weight precision',
    options: [
      { value: 'fp16', label: 'FP16 · 2 bytes' },
      { value: 'fp8', label: 'FP8 · 1 byte' },
      { value: 'int4', label: 'INT4 · ~0.5 byte' },
    ],
  },
  kvPrecision: {
    label: 'KV cache precision',
    options: [
      { value: 'fp16', label: 'FP16 · 2 bytes' },
      { value: 'fp8', label: 'FP8 · 1 byte' },
    ],
  },
  contextLength: {
    label: 'Context length (tokens per conversation)',
    options: [4096, 8192, 16384, 32768, 65536].map(v => ({ value: v, label: `${v / 1024}k` })),
  },
  concurrency: {
    label: 'Concurrent streams (users generating at once)',
    options: [1, 8, 16, 32, 64, 128].map(v => ({ value: v, label: String(v) })),
  },
  tensorParallel: {
    label: 'Tensor parallel size',
    options: [{ value: 'auto', label: 'Auto' }, ...[2, 4, 8].map(v => ({ value: v, label: `TP=${v}` }))],
    get: (c) => (c.isAutoSharding ? 'auto' : c.manualTp),
    set: (v) => (v === 'auto' ? { isAutoSharding: true, isAutoDp: true } : { isAutoSharding: false, manualTp: v, manualPp: 1, manualDp: 1 }),
  },
  selectedPlatformId: {
    label: 'GPU server',
    options: [
      { value: 'cisco-c885a-h100', label: 'UCS C885A · 8× H100 80 GB' },
      { value: 'cisco-c885a-h200', label: 'UCS C885A · 8× H200 141 GB' },
      { value: 'cisco-c885a-b200', label: 'UCS C885A · 8× B200 180 GB' },
    ],
    // Switching server also switches to that GPU's catalog price, as in Advanced mode.
    set: (v) => {
      const pricing = GPU_PRICING[PLATFORM_SYSTEMS.find(p => p.id === v)?.gpuId];
      return pricing
        ? { selectedPlatformId: v, gpuUnitPriceUsd: pricing.estimatedUnitPriceUsd, cloudRateUsdPerHr: pricing.estimatedCloudRateUsdPerHr }
        : { selectedPlatformId: v };
    },
  },
  peakActiveUsers: {
    label: 'Active users in the busiest hour',
    options: [100, 500, 5000].map(v => ({ value: v, label: v.toLocaleString() })),
  },
  requestsPerUserPerHour: {
    label: 'Requests per user per hour',
    options: [{ value: 10, label: '10 (chat)' }, { value: 60, label: '60 (coding / agents)' }],
  },
  targetUtilization: {
    label: 'Target utilization',
    options: [{ value: 0.5, label: '50%' }, { value: 0.7, label: '70%' }],
  },
  manualDp: {
    label: 'Cluster size (8-GPU tensor-parallel groups)',
    options: [4, 8, 16, 32].map(v => ({ value: v, label: `${v * 8} GPUs` })),
  },
  oversubscriptionRatio: {
    label: 'Leaf-to-spine oversubscription',
    options: [1, 2, 3].map(v => ({ value: v, label: `${v}:1` })),
  },
  coolingType: {
    label: 'Cooling',
    options: [{ value: 'air', label: 'Air · PUE 1.35 · 28 kW racks' }, { value: 'liquid', label: 'Liquid · PUE 1.15 · 80 kW racks' }],
    set: (v) => (v === 'liquid' ? { coolingType: 'liquid', pue: 1.15, rackPowerKw: 80 } : { coolingType: 'air', pue: 1.35, rackPowerKw: 28 }),
  },
  rackPowerKw: {
    label: 'Rack power limit',
    options: [15, 28, 40, 80].map(v => ({ value: v, label: `${v} kW` })),
  },
  zeroStage: {
    label: 'ZeRO sharding stage',
    options: [0, 1, 2, 3].map(v => ({ value: v, label: v === 0 ? 'Off' : `ZeRO-${v}` })),
  },
  trainingType: {
    label: 'Training method',
    options: [{ value: 'pretrain_sft', label: 'Full fine-tune' }, { value: 'lora', label: 'LoRA' }],
  },
  trainingTokensB: {
    label: 'Training tokens',
    options: [10, 100].map(v => ({ value: v, label: `${v}B` })),
  },
  gpuUnitPriceUsd: {
    label: 'GPU price (illustrative)',
    options: [25000, 35000, 45000].map(v => ({ value: v, label: `$${v / 1000}k` })),
  },
  dutyCyclePct: {
    label: 'Utilization (share of hours at full load)',
    options: [20, 50, 80].map(v => ({ value: v, label: `${v}%` })),
  },
  tcoYears: {
    label: 'Ownership horizon',
    options: [1, 3, 5].map(v => ({ value: v, label: `${v} year${v > 1 ? 's' : ''}` })),
  },
  enableNvidiaAiEnterprise: {
    label: 'NVIDIA AI Enterprise licences',
    options: [{ value: true, label: 'Included' }, { value: false, label: 'Not included' }],
  },
};

/** The option list a lesson shows for a control (optionally a subset). */
export function controlOptions(entry) {
  const id = typeof entry === 'string' ? entry : entry.id;
  const all = CONTROLS[id].options;
  return typeof entry === 'string' || !entry.only ? all : all.filter(o => entry.only.includes(o.value));
}
export const controlId = (entry) => (typeof entry === 'string' ? entry : entry.id);
export const controlValue = (id, c) => (CONTROLS[id].get ? CONTROLS[id].get(c) : c[id]);
export const controlSet = (id, v) => (CONTROLS[id].set ? CONTROLS[id].set(v) : { [id]: v });

export const LESSONS = {
  memory: {
    id: 'memory',
    objective: 'Estimate how much GPU memory a model\'s weights need, and see how precision decides how many GPUs a model must be split across.',
    design: 'Cisco UCS C885A M8 with eight NVIDIA H200 GPUs (141 GB each), the 8-GPU building block used in Cisco\'s validated AI infrastructure designs.',
    start: () => lessonBase('ent-rag-assistant', { selectedModelId: 'llama33-70b', selectedPrecisionId: 'fp16', kvPrecision: 'fp16', concurrency: 1, contextLength: 4096 }),
    controls: ['selectedModelId', 'selectedPrecisionId'],
    metrics: ['weightsTotal', 'usablePerGpu', 'gpus', 'sharding'],
    math: (s, c) => {
      const bytes = s.precision.bytesPerParam;
      const core = s.model.params * bytes;
      const extra = s.memory.weightTotalGb - core;
      return [
        { label: 'Weights', expr: `${s.model.params}B parameters × ${bytes} bytes`, value: gb(core) },
        ...(extra > 0.05 ? [{ label: '+ 16-bit layers', expr: 'embedding and output layers stay at 16-bit', value: gb(extra) }] : []),
        { label: '= Model weights', expr: '', value: gb(s.memory.weightTotalGb), strong: true },
        { label: 'Usable per GPU', expr: `${s.gpu.vramGb} GB × 90% runtime reserve × ${100 - c.memoryHeadroomPct}% headroom margin`, value: gb(s.memory.usableGpuCapacityGb) },
        { label: 'Minimum GPUs', expr: `${gb(s.memory.weightTotalGb)} ÷ ${gb(s.memory.usableGpuCapacityGb)}, rounded up to a valid split`, value: `${s.results.totalGpus}`, strong: true },
      ];
    },
    steps: [
      {
        kind: 'read',
        title: 'What a GPU has to hold',
        body: 'To serve a model, every GPU in the design must hold its share of the model\'s weights in high-bandwidth memory (HBM), plus working memory for the conversations it is serving. Weights come first: they are the fixed cost of running the model at all, before a single user connects.\n\nThe design you are working on is a single Cisco UCS C885A M8 node with eight NVIDIA H200 GPUs. Each H200 has 141 GB of HBM3e.',
        highlight: ['weightsTotal'],
      },
      {
        kind: 'predict',
        title: 'Predict: weights at FP16',
        body: 'Llama 3.3 70B has 70.6 billion parameters. At FP16 (also written BF16), each parameter takes 2 bytes.',
        question: 'About how much memory do the weights need?',
        options: ['~35 GB', '~71 GB', '~141 GB', '~280 GB'],
        answer: 2,
        explain: '70.6 billion × 2 bytes = 141.2 GB. The rule of thumb for any dense model: billions of parameters × bytes per parameter = GB of weights.',
        highlight: ['weightsTotal'],
      },
      {
        kind: 'read',
        title: 'One 141 GB GPU is not enough for 141 GB of weights',
        body: 'Not all of a GPU\'s memory is usable. Serving engines such as vLLM reserve about 10% for the CUDA runtime and fragmentation, and the calculator keeps a further 5% margin, leaving about 120 GB on an H200.\n\n141 GB of weights will not fit in 120 GB, so the calculator splits the model across two GPUs with tensor parallelism (TP=2). Lesson 3 covers how that split works.',
        highlight: ['usablePerGpu', 'gpus'],
      },
      {
        kind: 'task',
        title: 'Halve the weights with FP8',
        body: 'H200 GPUs have native FP8 Tensor Cores, and FP8 is the usual choice for serving on Hopper: accuracy stays close to FP16 for most models.',
        task: 'Change the weight precision to FP8.',
        check: (c) => c.selectedModelId === 'llama33-70b' && c.selectedPrecisionId === 'fp8',
        hint: 'Use the Weight precision control and keep the model on Llama 3.3 70B.',
        done: 'The weights drop to about 72.7 GB and the model now fits on one GPU. It is slightly more than 70.6 GB because the embedding and output layers stay at 16-bit.',
        highlight: ['weightsTotal', 'gpus'],
      },
      {
        kind: 'predict',
        title: 'Predict: a 405B model at FP8',
        body: 'Llama 3.1 405B has 405 billion parameters.',
        question: 'At FP8, about how much memory do its weights need?',
        options: ['~200 GB', '~405 GB', '~810 GB', '~1.6 TB'],
        answer: 1,
        explain: '405 billion × 1 byte ≈ 405 GB, plus about 4 GB for the 16-bit embedding and output layers.',
      },
      {
        kind: 'task',
        title: 'Size the 405B model',
        body: 'Now see how many GPUs that takes.',
        task: 'Select Llama 3.1 405B and keep FP8.',
        check: (c) => c.selectedModelId === 'llama3-405b' && c.selectedPrecisionId === 'fp8',
        hint: 'Use the Model control; precision should still read FP8.',
        done: 'About 409 GB of weights need four H200s (TP=4). At FP16 the same model needs all eight GPUs in the node, so precision alone decides whether a 405B model fits in half a node or a whole one.',
        highlight: ['weightsTotal', 'gpus', 'sharding'],
      },
      {
        kind: 'task',
        title: 'Go further with 4-bit',
        body: 'Weight-only 4-bit formats (AWQ, GPTQ) shrink weights to about half a byte per parameter. They trade some accuracy for memory, and on Hopper the math still runs at 16-bit. Blackwell GPUs add native FP4 (NVFP4) Tensor Cores.',
        task: 'Select Llama 3.3 70B at INT4.',
        check: (c) => c.selectedModelId === 'llama33-70b' && c.selectedPrecisionId === 'int4',
        hint: 'Set the Model back to Llama 3.3 70B and choose INT4.',
        done: 'About 40 GB: the same 70B model in under a third of one H200. The memory left over is what serves users, which is the subject of the next lesson.',
        highlight: ['weightsTotal'],
      },
      {
        kind: 'recap',
        title: 'Recap',
        points: [
          'Weights (GB) ≈ billions of parameters × bytes per parameter.',
          'Only about 85-90% of GPU memory is usable once runtime reserves are counted.',
          'FP8 halves weight memory versus FP16 and is the usual choice on H200; 4-bit halves it again at some accuracy cost.',
          'Precision decides how many GPUs a model must be split across before any user is served.',
        ],
      },
    ],
  },

  'kv-cache': {
    id: 'kv-cache',
    objective: 'Calculate the KV cache per token and per conversation, and see why context length and concurrency, not the model, usually decide the GPU count.',
    design: 'Llama 3.3 70B at FP8 on a Cisco UCS C885A M8 with eight NVIDIA H200 GPUs, the starting point of the Departmental RAG Assistant validated preset.',
    start: () => lessonBase('ent-rag-assistant', { selectedModelId: 'llama33-70b', selectedPrecisionId: 'fp8', kvPrecision: 'fp16', concurrency: 1, contextLength: 8192 }),
    controls: ['contextLength', 'concurrency', 'kvPrecision'],
    metrics: ['kvPerToken', 'kvPerStream', 'kvAllStreams', 'weightsTotal', 'gpus', 'sharding', 'usedPerGpu'],
    math: (s, c) => {
      const m = s.model;
      const kvBytes = c.kvPrecision === 'fp8' ? 1 : 2;
      const perToken = s.memory.bytesPerTokenSeq;
      return [
        { label: 'Per token', expr: `2 (K and V) × ${m.layers} layers × ${m.kvHeads} KV heads × ${m.headDim} dims × ${kvBytes} bytes`, value: `${perToken.toLocaleString()} bytes` },
        { label: 'Per stream', expr: `${perToken.toLocaleString()} bytes × ${c.contextLength.toLocaleString()} tokens`, value: gb(perToken * c.contextLength / 1e9) },
        { label: 'All streams', expr: `× ${c.concurrency} concurrent streams`, value: gb(perToken * c.contextLength * c.concurrency / 1e9), strong: true },
        { label: 'Weights', expr: 'from lesson 1 (held once per replica)', value: gb(s.memory.weightTotalGb) },
      ];
    },
    steps: [
      {
        kind: 'read',
        title: 'Memory that grows with every user',
        body: 'As a model reads a prompt and writes an answer, it keeps a key and a value vector for every token, in every layer, so it never recomputes them. This is the KV cache. Unlike the weights, which are held once, the KV cache grows with the length of each conversation and with the number of conversations running at once.',
        highlight: ['kvPerToken'],
      },
      {
        kind: 'read',
        title: 'KV cache per token',
        body: 'For Llama 3.3 70B: 2 (a key and a value) × 80 layers × 8 KV heads × 128 dimensions × 2 bytes at FP16 = 327,680 bytes, about 0.33 MB per token.\n\nThe model has 64 attention heads but only 8 KV heads: grouped-query attention (GQA) lets 8 query heads share each KV head, which makes the cache 8× smaller than it would otherwise be. Open "Show the math" to follow the calculation live.',
        highlight: ['kvPerToken'],
      },
      {
        kind: 'predict',
        title: 'Predict: one conversation',
        body: 'One user has an 8,192-token conversation (prompt plus answer).',
        question: 'How much KV cache does that one conversation hold?',
        options: ['~0.3 GB', '~2.7 GB', '~27 GB', '~270 GB'],
        answer: 1,
        explain: '327,680 bytes × 8,192 tokens ≈ 2.7 GB for a single conversation.',
        highlight: ['kvPerStream'],
      },
      {
        kind: 'task',
        title: 'Add users',
        body: 'Every concurrent stream holds its own cache.',
        task: 'Raise concurrent streams to 8.',
        check: (c) => c.concurrency >= 8,
        hint: 'Use the Concurrent streams control.',
        done: 'Eight conversations hold about 21.5 GB of KV. With 72.7 GB of weights, the design still fits on one H200.',
        highlight: ['kvAllStreams', 'usedPerGpu', 'gpus'],
      },
      {
        kind: 'task',
        title: 'Lengthen the conversations',
        body: 'Document assistants and coding tools routinely use 32k-token contexts or more.',
        task: 'With 8 streams, raise the context length to 32k.',
        check: (c) => c.concurrency >= 8 && c.contextLength >= 32768,
        hint: 'Keep 8 streams and set Context length to 32k.',
        done: 'KV cache quadruples to about 86 GB, more than the weights. The design now needs two GPUs: the calculator adds a second replica (DP=2) because the extra memory is needed for conversations, not the model.',
        highlight: ['kvAllStreams', 'weightsTotal', 'gpus'],
      },
      {
        kind: 'predict',
        title: 'Predict: 64 users at 32k',
        body: 'Each 32k conversation holds about 10.7 GB of KV.',
        question: 'Roughly how many H200s do 64 concurrent 32k conversations need?',
        options: ['2', 'About 4', 'About 8', 'It cannot be served'],
        answer: 2,
        explain: '64 × 10.7 GB ≈ 687 GB of KV, about ten times the weights. At about 120 GB usable per GPU that is at least six GPUs before counting weights; the calculator lands on eight.',
      },
      {
        kind: 'task',
        title: 'Scale to 64 users',
        body: 'Check the prediction against the calculator.',
        task: 'Raise concurrent streams to 64 (context still 32k).',
        check: (c) => c.concurrency >= 64 && c.contextLength >= 32768 && c.kvPrecision === 'fp16',
        hint: 'Set Concurrent streams to 64 and keep KV cache precision at FP16.',
        done: 'A full node: eight GPUs, almost all of it KV cache. For long-context, multi-user services the KV cache, not the model, sets the GPU count.',
        highlight: ['kvAllStreams', 'gpus', 'sharding'],
      },
      {
        kind: 'task',
        title: 'Halve the cache with FP8 KV',
        body: 'Serving engines can store the KV cache in FP8 (vLLM: --kv-cache-dtype fp8) with little quality loss on most models.',
        task: 'Switch the KV cache precision to FP8.',
        check: (c) => c.concurrency >= 64 && c.contextLength >= 32768 && c.kvPrecision === 'fp8',
        hint: 'Use the KV cache precision control; keep 64 streams at 32k.',
        done: 'The per-token cache halves to about 0.16 MB and the design drops from eight GPUs to four: the same service on half the hardware.',
        highlight: ['kvPerToken', 'gpus'],
      },
      {
        kind: 'recap',
        title: 'Recap',
        points: [
          'KV per token = 2 × layers × KV heads × head dimension × bytes; grouped-query attention keeps it small.',
          'KV cache = per token × context length × concurrent streams, so it grows with both.',
          'For long-context, multi-user services the KV cache usually outweighs the model and sets the GPU count.',
          'FP8 KV halves the cache; prefix caching (shared prompts held once) is the other big lever, available in Advanced mode.',
          'This is why validated designs for document and coding assistants favour high-memory GPUs such as the 141 GB H200 and 180 GB B200.',
        ],
      },
    ],
  },

  sharding: {
    id: 'sharding',
    objective: 'Choose between tensor, pipeline and data parallelism, and see why tensor parallelism stays inside one NVLink-connected server.',
    design: 'Llama 3.1 405B at FP8 on a Cisco UCS C885A M8 GPU server: eight GPUs joined by NVLink inside the chassis, and one 400G network port per GPU to the rest of the cluster.',
    start: () => lessonBase('ent-rag-assistant', { selectedModelId: 'llama3-405b', selectedPrecisionId: 'fp8', kvPrecision: 'fp8', concurrency: 16, contextLength: 8192, isAutoSharding: true, isAutoDp: true }),
    controls: ['tensorParallel', { id: 'concurrency', only: [16, 64, 128] }, { id: 'selectedPrecisionId', only: ['fp8', 'fp16'] }, { id: 'selectedPlatformId', only: ['cisco-c885a-h200', 'cisco-c885a-h100'] }],
    metrics: ['weightsTotal', 'weightsPerGpu', 'usedPerGpu', 'gpus', 'sharding', 'nodes'],
    math: (s) => [
      { label: 'Weights', expr: 'from lesson 1', value: gb(s.memory.weightTotalGb) },
      { label: 'Per GPU', expr: `÷ TP ${s.tp}${s.pp > 1 ? ` ÷ PP ${s.pp}` : ''} (each GPU holds a slice)`, value: gb(s.memory.perGpuWeightsGb) },
      { label: 'Usable per GPU', expr: `${s.gpu.name.split(' (')[0]}, after runtime reserve`, value: gb(s.memory.usableGpuCapacityGb) },
      { label: 'Replica', expr: `TP ${s.tp} × PP ${s.pp} GPUs hold one full copy`, value: `${s.tp * s.pp} GPUs` },
      { label: 'Total', expr: `× DP ${s.dp} replicas`, value: `${s.results.totalGpus} GPUs`, strong: true },
    ],
    steps: [
      {
        kind: 'read',
        title: 'Three ways to split the work',
        body: 'Tensor parallelism (TP) splits every layer across GPUs; they exchange partial results twice per layer, so TP needs the 900 GB/s NVLink inside a server, not the ~50 GB/s of a 400G network port.\n\nPipeline parallelism (PP) gives each GPU group a range of layers and passes activations between stages once per step, so it can cross servers.\n\nData parallelism (DP) runs complete, independent copies (replicas) of the model, each serving its own users. Validated designs keep TP inside the 8-GPU server and scale out with DP, adding PP only when a model is too big for one server.',
        highlight: ['sharding'],
      },
      {
        kind: 'predict',
        title: 'Predict: the smallest split',
        body: 'Llama 3.1 405B at FP8 needs about 409 GB of weights, and each H200 has about 120 GB usable.',
        question: 'What is the smallest tensor-parallel size that can hold it?',
        options: ['TP=2', 'TP=4', 'TP=8', 'It needs two servers'],
        answer: 1,
        explain: '409 GB ÷ 4 ≈ 102 GB per GPU fits in 120 GB, leaving room for the KV cache. At TP=2 each GPU would need about 205 GB.',
        highlight: ['weightsPerGpu'],
      },
      {
        kind: 'task',
        title: 'Try a split that is too small',
        body: 'Override the solver to see what happens.',
        task: 'Set the tensor parallel size to TP=2.',
        check: (c, s) => !c.isAutoSharding && c.manualTp === 2 && s.memory.isOOM,
        hint: 'Choose TP=2 under Tensor parallel size (keep 16 streams, FP8 and H200).',
        done: 'Each GPU would need over 220 GB: the design does not fit. No amount of extra servers helps a replica whose slice is too big for one GPU.',
        highlight: ['weightsPerGpu', 'usedPerGpu'],
      },
      {
        kind: 'task',
        title: 'Use the whole server',
        body: 'A larger TP gives each GPU a smaller slice.',
        task: 'Set TP=8.',
        check: (c, s) => !c.isAutoSharding && c.manualTp === 8 && !s.memory.isOOM,
        hint: 'Choose TP=8 under Tensor parallel size.',
        done: 'About 51 GB of weights per GPU: the model fits comfortably, with plenty of memory left for conversations, and (as lesson 4 shows) each token is generated faster. The cost is that all eight GPUs serve one replica.',
        highlight: ['weightsPerGpu', 'gpus'],
      },
      {
        kind: 'task',
        title: 'Let the solver scale out',
        body: 'Hand the choice back to the calculator and add users.',
        task: 'Set tensor parallel size to Auto and raise concurrent streams to 64.',
        check: (c) => c.isAutoSharding && c.concurrency === 64 && c.selectedPrecisionId === 'fp8' && c.selectedPlatformId === 'cisco-c885a-h200',
        hint: 'Choose Auto, then 64 streams.',
        done: 'The solver keeps TP=4 and adds a second replica (DP=2): eight GPUs, each replica serving 32 users with its own copy of the weights.',
        highlight: ['sharding', 'gpus'],
      },
      {
        kind: 'predict',
        title: 'Predict: 128 users',
        body: 'Each TP=4 replica spends about 102 GB per GPU on weights, leaving little for the KV cache of its users.',
        question: 'With 128 streams, which layout needs the fewest GPUs?',
        options: ['TP=4 × DP=4 (16 GPUs)', 'TP=8 × DP=1 (8 GPUs)', 'TP=4 × DP=3 (12 GPUs)', 'TP=8 × PP=2 (16 GPUs)'],
        answer: 1,
        explain: 'At TP=8 the weights are held once across the server (about 51 GB per GPU), leaving roughly 70 GB per GPU for KV cache: enough for all 128 streams on eight GPUs. More replicas would store the 409 GB of weights again for each one.',
      },
      {
        kind: 'task',
        title: 'Check the prediction',
        body: 'The solver tries each tensor-parallel size inside the server and keeps the layout with the fewest GPUs.',
        task: 'Raise concurrent streams to 128 (Auto, FP8, H200).',
        check: (c) => c.isAutoSharding && c.concurrency === 128 && c.selectedPrecisionId === 'fp8' && c.selectedPlatformId === 'cisco-c885a-h200',
        hint: 'Choose 128 streams with the tensor parallel size on Auto.',
        done: 'TP=8, one replica, eight GPUs: for many concurrent users on a large model, one wide replica holds the weights once and leaves the most memory for the KV cache.',
        highlight: ['sharding', 'gpus'],
      },
      {
        kind: 'task',
        title: 'When one server is not enough',
        body: 'Switch to the H100 server (80 GB per GPU) and full 16-bit precision.',
        task: 'Select the H100 server and FP16, with 16 streams and Auto.',
        check: (c) => c.isAutoSharding && c.concurrency === 16 && c.selectedPrecisionId === 'fp16' && c.selectedPlatformId === 'cisco-c885a-h100',
        hint: 'Set GPU server to H100, precision to FP16, streams to 16 and tensor parallel size to Auto.',
        done: '810 GB of weights exceed the ~547 GB usable in one 8× H100 server, so the calculator adds pipeline parallelism: TP=8 inside each server × PP=2 across two servers, joined by the network fabric. Lesson 6 covers that fabric.',
        highlight: ['sharding', 'nodes', 'gpus'],
      },
      {
        kind: 'recap',
        title: 'Recap',
        points: [
          'TP splits every layer and needs NVLink: keep it inside the 8-GPU server.',
          'PP splits layers into stages and can cross servers; use it only when a model will not fit in one server.',
          'DP adds complete replicas for more users, but each holds its own copy of the weights.',
          'For large models with many users, one wide TP=8 replica often needs fewer GPUs than several narrow ones.',
        ],
      },
    ],
  },

  speed: {
    id: 'speed',
    objective: 'Estimate time to first token and time per output token, and know which hardware choice moves each one.',
    design: 'Llama 3.3 70B at FP8 on a Cisco UCS C885A M8, 8,192-token requests (about 6,550 prompt tokens and a 1,640-token answer).',
    start: () => lessonBase('ent-rag-assistant', { selectedModelId: 'llama33-70b', selectedPrecisionId: 'fp8', kvPrecision: 'fp8', concurrency: 1, contextLength: 8192, promptTokenRatio: 0.8, isAutoSharding: true, isAutoDp: true }),
    controls: [{ id: 'concurrency', only: [1, 32] }, { id: 'tensorParallel', only: ['auto', 2, 4] }, { id: 'selectedPlatformId', only: ['cisco-c885a-h200', 'cisco-c885a-b200'] }, { id: 'contextLength', only: [8192, 32768] }],
    metrics: ['ttft', 'tpot', 'tokPerStream', 'clusterTps', 'gpus', 'sharding'],
    math: (s) => {
      const t = s.throughput;
      const peak = t.gpuTflops;
      const mfu = t.t_compute > 0 ? (Number(t.promptPflops) * 1e15) / (t.t_compute * s.tp * peak * 1e12) : 0;
      return [
        { label: 'Prefill work', expr: 'prompt tokens × 2 × parameters, plus attention', value: `${t.promptPflops} PFLOP` },
        { label: 'Prefill rate', expr: `TP ${s.tp} × ${peak.toLocaleString()} TFLOPS × ${Math.round(mfu * 100)}% utilization`, value: `${((s.tp * peak * mfu) / 1000).toFixed(2)} PFLOP/s` },
        { label: 'Time to first token', expr: 'work ÷ rate (+ TP communication)', value: sec(t.ttftSec), strong: true },
        { label: 'Decode memory time', expr: `read weights + batch KV per step, ${s.gpu.memBandwidthTbps} TB/s per GPU × TP ${s.tp}`, value: `${(t.t_mem * 1000).toFixed(1)} ms` },
        { label: 'Decode compute time', expr: '2 × parameters × streams in the batch', value: `${(t.t_comp * 1000).toFixed(1)} ms` },
        { label: 'Time per token', expr: 'the larger of the two, plus TP communication', value: `${Number(t.tpotMs).toFixed(1)} ms`, strong: true },
      ];
    },
    steps: [
      {
        kind: 'read',
        title: 'Two phases, two bottlenecks',
        body: 'Prefill reads the whole prompt at once: thousands of tokens per weight read, so it is limited by compute (TFLOPS). It sets the time to first token (TTFT).\n\nDecode then produces one token per step for each user, and every step has to read all the weights and each conversation\'s KV cache from memory. It is limited by memory bandwidth (TB/s), and it sets the time per output token (TPOT). Around 50 ms per token (20 tokens a second) reads faster than people do.',
        highlight: ['ttft', 'tpot'],
      },
      {
        kind: 'predict',
        title: 'Predict: one user\'s speed',
        body: 'Each decode step reads about 71 GB of weights. An H200 moves 4.8 TB/s, and real kernels reach about 75% of that.',
        question: 'Roughly how long does each token take for a single user?',
        options: ['~2 ms', '~20 ms', '~200 ms', '~2 s'],
        answer: 1,
        explain: '71 GB ÷ (4.8 TB/s × 0.75) ≈ 20 ms, about 50 tokens a second. With one user the GPU\'s compute is almost idle: decode is bandwidth-bound.',
        highlight: ['tpot'],
      },
      {
        kind: 'read',
        title: 'Time to first token',
        body: 'Prefill here is about 1 PFLOP of work (6,550 prompt tokens × 2 × 70.6B parameters, plus attention). The H200 delivers 1,979 TFLOPS at FP8, and prefill reaches about half of that in practice, so the first token takes about 1 second. Open Show the math to see each term.',
        highlight: ['ttft'],
      },
      {
        kind: 'task',
        title: 'Batch 32 users',
        body: 'Serving engines batch many users into each decode step, so one weight read serves them all.',
        task: 'Raise concurrent streams to 32.',
        check: (c) => c.concurrency === 32 && c.isAutoSharding && c.selectedPlatformId === 'cisco-c885a-h200' && c.contextLength === 8192,
        hint: 'Choose 32 concurrent streams.',
        done: 'Each user slows to about 40 ms per token, because every step now also reads 32 conversations\' KV cache, but total output rises from about 50 to about 810 tokens a second on the same GPU. Batching trades a little per-user speed for a lot of throughput.',
        highlight: ['tpot', 'clusterTps'],
      },
      {
        kind: 'task',
        title: 'Add tensor parallelism',
        body: 'Two GPUs working on each step read the weights in parallel.',
        task: 'With 32 streams, set tensor parallel size to TP=2.',
        check: (c) => c.concurrency === 32 && !c.isAutoSharding && c.manualTp === 2 && c.selectedPlatformId === 'cisco-c885a-h200' && c.contextLength === 8192,
        hint: 'Choose TP=2 under Tensor parallel size.',
        done: 'Time per token falls to about 22 ms and time to first token to about 0.54 s: TP doubles both the bandwidth and the compute working on each request.',
        highlight: ['tpot', 'ttft'],
      },
      {
        kind: 'predict',
        title: 'Predict: Blackwell',
        body: 'A B200 has 8 TB/s of memory bandwidth (1.7× the H200) and 4,500 TFLOPS of FP8 compute (2.3× the H200).',
        question: 'At TP=1 with 32 users, which improves more on B200?',
        options: ['Time to first token', 'Time per output token', 'Both by the same amount', 'Neither'],
        answer: 0,
        explain: 'Prefill is compute-bound, so it gains the full 2.3×; decode is bandwidth-bound, so it gains closer to 1.7×.',
      },
      {
        kind: 'task',
        title: 'Check on B200',
        body: 'Switch the server and let the solver choose TP again.',
        task: 'Select the B200 server, set tensor parallel size to Auto, 32 streams.',
        check: (c) => c.concurrency === 32 && c.isAutoSharding && c.selectedPlatformId === 'cisco-c885a-b200' && c.contextLength === 8192,
        hint: 'Set GPU server to B200 and tensor parallel size to Auto.',
        done: 'Time to first token falls from about 1.0 s to about 0.44 s (2.3×); time per token from about 40 ms to about 24 ms (1.7×). Match the GPU to the bottleneck your users feel.',
        highlight: ['ttft', 'tpot'],
      },
      {
        kind: 'task',
        title: 'Long prompts',
        body: 'Document and coding assistants send much longer prompts.',
        task: 'On B200 with 32 streams, raise the context length to 32k.',
        check: (c) => c.concurrency === 32 && c.isAutoSharding && c.selectedPlatformId === 'cisco-c885a-b200' && c.contextLength === 32768,
        hint: 'Set Context length to 32k.',
        done: 'Prefill work grows about five-fold (four times the tokens, plus attention that grows with length), and the extra KV cache pushes the design to two GPUs at TP=2. Long-context services are where prefill speed and memory both start to dominate.',
        highlight: ['ttft', 'gpus'],
      },
      {
        kind: 'recap',
        title: 'Recap',
        points: [
          'TTFT ≈ prefill FLOPs ÷ (TFLOPS × utilization): compute-bound, grows with prompt length.',
          'TPOT ≈ bytes read per step ÷ memory bandwidth: bandwidth-bound, grows with batch size and context.',
          'Batching multiplies throughput for a modest per-user slowdown; TP speeds up both phases.',
          'Newer GPUs gain more on compute than on bandwidth, so they help prefill-heavy workloads most.',
        ],
      },
    ],
  },

  traffic: {
    id: 'traffic',
    objective: 'Turn a customer\'s user count into requests per second, requests in flight and GPUs, and understand why utilization targets exist.',
    design: 'Llama 3.3 70B at FP8 on Cisco UCS C885A M8 H200 servers, sized from peak-hour users rather than concurrent streams.',
    start: () => lessonBase('ent-rag-assistant', { selectedModelId: 'llama33-70b', selectedPrecisionId: 'fp8', kvPrecision: 'fp8', contextLength: 8192, promptTokenRatio: 0.8, sizingInputMode: 'traffic', trafficInputType: 'users', peakActiveUsers: 500, requestsPerUserPerHour: 10, targetUtilization: 0.7, isAutoSharding: true, isAutoDp: true }),
    controls: ['peakActiveUsers', 'requestsPerUserPerHour', 'targetUtilization'],
    metrics: ['rps', 'serviceTime', 'inFlight', 'gpus', 'sharding', 'p99Ttft'],
    math: (s, c) => {
      const t = s.traffic;
      return [
        { label: 'Request rate', expr: `${c.peakActiveUsers.toLocaleString()} users × ${c.requestsPerUserPerHour} per hour ÷ 3,600`, value: `${t.requestsPerSec.toFixed(2)} /s` },
        { label: 'Time per request', expr: `first token + answer tokens × ${Number(s.throughput.tpotMs).toFixed(1)} ms`, value: sec(t.serviceTimeSec) },
        { label: 'In flight (average)', expr: 'rate × time per request (Little\'s law)', value: (t.requestsPerSec * t.serviceTimeSec).toFixed(0) },
        { label: 'Sized for', expr: `÷ ${Math.round(t.targetUtilization * 100)}% target utilization`, value: t.concurrency.toLocaleString(), strong: true },
      ];
    },
    steps: [
      {
        kind: 'read',
        title: 'Customers count users, not streams',
        body: 'A customer will tell you "500 people will use it" or "we expect 20 requests an hour per engineer". The design has to hold the requests that are running at the same moment, so the first step is converting users into a request rate.',
        highlight: ['rps'],
      },
      {
        kind: 'predict',
        title: 'Predict: the request rate',
        body: '500 users in the busiest hour each send 10 requests an hour.',
        question: 'What is the peak request rate?',
        options: ['~0.14 per second', '~1.4 per second', '~14 per second', '~83 per second'],
        answer: 1,
        explain: '500 × 10 = 5,000 requests an hour ÷ 3,600 seconds ≈ 1.39 requests per second.',
        highlight: ['rps'],
      },
      {
        kind: 'read',
        title: 'Little\'s law',
        body: 'The average number of requests in the system equals the arrival rate times the time each one spends there. Each request takes about 68 seconds here: about 1 s to the first token, then a 1,640-token answer at about 40 ms per token.\n\n1.39 per second × 68 s ≈ 94 requests in flight on average. Traffic arrives in bursts, so the design is sized so that this average is only 70% of capacity: about 135 requests. Open Show the math to follow it.',
        highlight: ['serviceTime', 'inFlight'],
      },
      {
        kind: 'task',
        title: 'Ten times the users',
        body: 'Scale the service to a whole division.',
        task: 'Raise active users to 5,000.',
        check: (c) => c.peakActiveUsers === 5000 && c.requestsPerUserPerHour === 10 && c.targetUtilization === 0.7,
        hint: 'Choose 5,000 users (10 requests per hour, 70% utilization).',
        done: 'About 13.9 requests a second and about 1,550 requests in flight: 24 GPUs in six TP=4 replicas.',
        highlight: ['rps', 'inFlight', 'gpus'],
      },
      {
        kind: 'predict',
        title: 'Predict: who waits longer?',
        body: 'Both designs run at the same 70% utilization. The 500-user design has 4 replicas; the 5,000-user design has 6 much larger ones.',
        question: 'Which has the longer P99 (worst 1 in 100) time to first token?',
        options: ['500 users', '5,000 users', 'The same', 'Neither ever waits'],
        answer: 0,
        explain: 'The 500-user design sees about 9 s at P99 against about 0.3 s for 5,000 users. A bigger pool absorbs bursts better, and requests that last over a minute make any queue slow to clear.',
        highlight: ['p99Ttft'],
      },
      {
        kind: 'task',
        title: 'Buy headroom',
        body: 'Back at 500 users, plan for a lower utilization.',
        task: 'Set 500 users and a 50% target utilization.',
        check: (c) => c.peakActiveUsers === 500 && c.requestsPerUserPerHour === 10 && c.targetUtilization === 0.5,
        hint: 'Choose 500 users and 50%.',
        done: 'The design must now hold about 196 requests. The solver reshapes the same four GPUs into two faster TP=2 replicas, and the P99 time to first token drops from about 9 s to about 0.5 s.',
        highlight: ['inFlight', 'p99Ttft', 'sharding'],
      },
      {
        kind: 'task',
        title: 'Busier users',
        body: 'Coding assistants and agents send far more requests per user.',
        task: 'Set 500 users, 60 requests per user per hour and 70% utilization.',
        check: (c) => c.peakActiveUsers === 500 && c.requestsPerUserPerHour === 60 && c.targetUtilization === 0.7,
        hint: 'Choose 500 users, 60 requests per hour and 70%.',
        done: 'About 8.3 requests a second and about 1,000 in flight: 16 GPUs. How users work matters as much as how many there are.',
        highlight: ['rps', 'gpus'],
      },
      {
        kind: 'recap',
        title: 'Recap',
        points: [
          'Requests per second = users × requests per user per hour ÷ 3,600.',
          'Requests in flight = rate × time per request (Little\'s law); divide by a target utilization for headroom.',
          'Long requests and small pools make tail latency jump; plan 50-70% utilization for interactive services.',
          'Ask customers for usage patterns, not just user counts: agents and coding tools send many times more requests.',
        ],
      },
    ],
  },

  network: {
    id: 'network',
    objective: 'Size the GPU back-end fabric: NIC rails, leaf and spine switches, optics and oversubscription.',
    design: 'A full fine-tuning cluster of Cisco UCS C885A M8 servers (8× H100, one 400G NIC per GPU) on a lossless Ethernet (RoCEv2) back-end fabric of 64-port switches.',
    start: () => lessonBase('ent-full-finetune', {}),
    controls: ['manualDp', 'oversubscriptionRatio'],
    metrics: ['gpus', 'nodes', 'leaf', 'spine', 'transceivers', 'bisection'],
    math: (s, c) => [
      { label: 'GPU ports', expr: `${s.results.totalGpus} GPUs × one ${s.network.nicSpeedGbps}G NIC each`, value: `${s.network.totalComputeNics}` },
      { label: 'Leaf switches', expr: s.network.spineSwitches === 0 ? 'all ports fit on one 64-port switch' : '8 rails (one per GPU position) × enough leaves for every server', value: `${s.network.leafSwitches}` },
      { label: 'Spine switches', expr: s.network.spineSwitches === 0 ? 'none needed' : `leaf uplinks ÷ ${c.oversubscriptionRatio}:1 oversubscription`, value: `${s.network.spineSwitches}` },
      { label: 'Bisection', expr: `GPU ports × ${s.network.nicSpeedGbps}G ÷ 2, ÷ oversubscription`, value: `${s.network.effectiveBisectionTbps.toFixed(1)} Tbps`, strong: true },
    ],
    steps: [
      {
        kind: 'read',
        title: 'A fabric just for GPUs',
        body: 'Training exchanges gradients between every GPU on every step, so AI clusters have a dedicated back-end fabric: one 400G NIC per GPU, lossless, and non-blocking. Cisco\'s validated designs build it from Nexus 9000 400G switches running RoCEv2 (RDMA over Ethernet, made lossless with PFC and ECN); InfiniBand is the alternative. In the calculator both give the same topology and counts; the choice is about operations, tooling and cost.',
        highlight: ['gpus'],
      },
      {
        kind: 'predict',
        title: 'Predict: a small cluster',
        body: 'This cluster has 32 GPUs, each with one 400G port, and the switches have 64 ports.',
        question: 'How many switches does the GPU fabric need?',
        options: ['1', '2', '4', '8'],
        answer: 0,
        explain: '32 ports fit on a single 64-port leaf, so there is no spine layer at all. Up to 64 GPUs can share one switch.',
        highlight: ['leaf', 'spine'],
      },
      {
        kind: 'task',
        title: 'Grow past one switch',
        body: 'Double the cluster twice.',
        task: 'Set the cluster size to 128 GPUs.',
        check: (c) => c.manualDp === 16 && c.oversubscriptionRatio === 1,
        hint: 'Choose 128 GPUs (keep 1:1 oversubscription).',
        done: 'Past 64 GPUs a single switch runs out of ports, so the fabric becomes two tiers: 8 leaf switches and 4 spines, with 768 optical transceivers. Networking is now a real part of the bill of materials.',
        highlight: ['leaf', 'spine', 'transceivers'],
      },
      {
        kind: 'read',
        title: 'Rail-optimized design',
        body: 'The 8 leaves are rails: GPU 1 of every server connects to leaf 1, GPU 2 to leaf 2, and so on. Collective operations mostly exchange data between GPUs in the same position, so most traffic crosses a single switch; the spines carry the rest. At 1:1 every leaf has as much uplink capacity to the spines as it has GPU ports, so any GPU can talk to any other at full speed.',
        highlight: ['leaf', 'bisection'],
      },
      {
        kind: 'predict',
        title: 'Predict: oversubscription',
        body: 'At 2:1 oversubscription each leaf has half as much uplink capacity as GPU-facing capacity.',
        question: 'What does that change?',
        options: ['GPU NIC speed halves', 'Leaf count halves', 'Spines, optics and bisection bandwidth shrink', 'Nothing in the design'],
        answer: 2,
        explain: 'GPU ports stay at 400G, but fewer uplinks mean fewer spines and transceivers, and half the bandwidth across the middle of the fabric.',
      },
      {
        kind: 'task',
        title: 'Oversubscribe the spine',
        body: 'Check the saving and what it costs.',
        task: 'At 128 GPUs, set oversubscription to 2:1.',
        check: (c) => c.manualDp === 16 && c.oversubscriptionRatio === 2,
        hint: 'Choose 2:1 with 128 GPUs.',
        done: 'Spines drop from 4 to 2 and transceivers from 768 to 512, but bisection bandwidth halves from 51.2 to 25.6 Tbps. Acceptable for inference traffic; for training, a blocking fabric makes every all-reduce wait, so validated training designs stay at 1:1.',
        highlight: ['spine', 'transceivers', 'bisection'],
      },
      {
        kind: 'recap',
        title: 'Recap',
        points: [
          'One 400G (or 800G) NIC per GPU on a dedicated, lossless back-end fabric.',
          'Up to 64 GPUs fit on one 64-port leaf; beyond that, a rail-optimized leaf/spine design.',
          'Oversubscription saves spines and optics but cuts bisection bandwidth: fine for inference, avoid for training.',
          'RoCEv2 on Cisco Nexus and InfiniBand give the same topology; choose on operations and cost.',
        ],
      },
    ],
  },

  facility: {
    id: 'facility',
    objective: 'Work out IT and facility power, how many servers fit in a rack, and when a design needs liquid cooling.',
    design: 'A 64-GPU cluster (eight Cisco UCS C885A M8 servers) in a data hall at $0.12/kWh.',
    start: () => lessonBase('ent-full-finetune', { manualDp: 8, coolingType: 'air', pue: 1.35, rackPowerKw: 28 }),
    controls: [{ id: 'selectedPlatformId', only: ['cisco-c885a-h100', 'cisco-c885a-b200'] }, 'coolingType', 'rackPowerKw'],
    metrics: ['itPower', 'facilityPower', 'perRack', 'racks', 'energy', 'powerCost'],
    math: (s, c) => [
      { label: 'Servers', expr: `${s.results.nodes} × ${s.platform.chassisTdpKw} kW each`, value: `${(s.results.nodes * s.platform.chassisTdpKw).toFixed(1)} kW` },
      { label: '+ Network', expr: 'switches and optics', value: `${s.facility.networkPowerKw.toFixed(1)} kW` },
      { label: '= IT power', expr: '', value: `${s.facility.totalItPowerKw.toFixed(1)} kW` },
      { label: 'Facility power', expr: `× PUE ${c.pue.toFixed(2)} (cooling and losses)`, value: `${s.facility.totalFacilityPowerKw.toFixed(1)} kW`, strong: true },
      { label: 'Servers per rack', expr: `min(40 RU ÷ ${s.platform.chassisHeightRu || 8} RU, ${c.rackPowerKw} kW ÷ ${s.platform.chassisTdpKw} kW)`, value: `${s.facility.perRack}` },
    ],
    steps: [
      {
        kind: 'read',
        title: 'Power is the new floor space',
        body: 'An 8-GPU H100 server such as the Cisco UCS C885A M8 draws up to about 10.2 kW. The switches and optics add more. On top of that IT load the building spends power on cooling and conversion losses, measured as PUE (facility power ÷ IT power): about 1.35 for a typical air-cooled hall.',
        highlight: ['itPower', 'facilityPower'],
      },
      {
        kind: 'predict',
        title: 'Predict: the IT load',
        body: 'This cluster has eight 10.2 kW servers plus its network.',
        question: 'Roughly what is the IT load?',
        options: ['~40 kW', '~85 kW', '~150 kW', '~300 kW'],
        answer: 1,
        explain: '8 × 10.2 kW ≈ 82 kW of servers plus about 4 kW of network: about 85 kW, or about 115 kW at the facility meter with PUE 1.35.',
        highlight: ['itPower'],
      },
      {
        kind: 'task',
        title: 'An older data hall',
        body: 'Many enterprise halls were built for about 10-15 kW per rack.',
        task: 'Set the rack power limit to 15 kW.',
        check: (c) => c.rackPowerKw === 15 && c.selectedPlatformId === 'cisco-c885a-h100',
        hint: 'Choose 15 kW (keep the H100 server).',
        done: 'Only one 10.2 kW server fits per rack: the same eight servers now need 9 racks instead of 5. Power, not rack units, is what fills the room.',
        highlight: ['perRack', 'racks'],
      },
      {
        kind: 'task',
        title: 'Move to Blackwell',
        body: 'The B200 version of the server draws about 14.3 kW.',
        task: 'Select the B200 server with air cooling and 28 kW racks.',
        check: (c) => c.selectedPlatformId === 'cisco-c885a-b200' && c.coolingType === 'air' && c.rackPowerKw === 28,
        hint: 'Set GPU server to B200, Cooling to Air (which resets racks to 28 kW).',
        done: 'IT load rises to about 118 kW, and two 14.3 kW servers (28.6 kW) no longer fit a 28 kW rack: one server per rack again, 9 racks.',
        highlight: ['itPower', 'perRack', 'racks'],
      },
      {
        kind: 'predict',
        title: 'Predict: liquid cooling',
        body: 'Direct-to-chip liquid cooling supports about 80 kW per rack. Each 8 RU server draws 14.3 kW, and a rack has 40 usable RU.',
        question: 'How many B200 servers fit per rack?',
        options: ['2', '4', '5', '8'],
        answer: 2,
        explain: '80 kW ÷ 14.3 kW = 5.6, and 40 RU ÷ 8 RU = 5, so five servers: space and power now run out together.',
      },
      {
        kind: 'task',
        title: 'Switch to liquid',
        body: 'Liquid cooling also lowers PUE.',
        task: 'Set cooling to liquid with the B200 server.',
        check: (c) => c.selectedPlatformId === 'cisco-c885a-b200' && c.coolingType === 'liquid' && c.rackPowerKw === 80,
        hint: 'Choose Liquid under Cooling (it sets 80 kW racks and PUE 1.15).',
        done: 'Five servers per rack: 3 racks instead of 9. Facility power falls from about 160 kW to about 136 kW at PUE 1.15, saving about 200 MWh and $25,000 a year. Rack-scale systems such as GB200 NVL72 need about 120 kW per rack and are liquid-only.',
        highlight: ['perRack', 'racks', 'facilityPower', 'powerCost'],
      },
      {
        kind: 'recap',
        title: 'Recap',
        points: [
          'IT power = servers × nameplate kW + network; facility power = IT × PUE.',
          'Servers per rack = the lower of the rack-unit and the power limits; GPU servers usually hit power first.',
          'Blackwell-class servers exceed typical air-cooled rack budgets; liquid cooling fits more per rack and lowers PUE.',
          'Check the customer\'s rack power and cooling before choosing a GPU generation.',
        ],
      },
    ],
  },

  training: {
    id: 'training',
    objective: 'Size training memory with ZeRO sharding, estimate time to train, and account for failures.',
    design: 'Full fine-tuning of Llama 3.3 70B on Cisco UCS C885A M8 servers with 8× H100, TP=8 inside each server and data parallelism across servers.',
    start: () => lessonBase('ent-full-finetune', {}),
    controls: ['zeroStage', { id: 'trainingTokensB' }, { id: 'manualDp', only: [4, 16] }, 'trainingType'],
    metrics: ['trainingState', 'usedPerGpu', 'gpus', 'computeDays', 'wallDays', 'goodput'],
    math: (s, c) => {
      const t = s.trainingTime;
      const params = s.model.params;
      const factor = c.trainingType === 'lora' ? 4 : 6;
      return [
        { label: 'Training state', expr: c.trainingType === 'lora' ? 'frozen 16-bit weights + small adapters' : `${params}B × 16 bytes (weights, gradients, FP32 optimizer)`, value: gb(METRICS.trainingState.value(s), 0) },
        { label: 'Per GPU', expr: `ZeRO-${c.zeroStage} sharding over ${s.results.totalGpus} GPUs, plus activations`, value: gb(s.memory.perGpuTotalUsedGb) },
        { label: 'Compute', expr: `${factor} × ${params}B parameters × ${c.trainingTokensB}B tokens`, value: `${(t.totalFlops / 1e21).toFixed(1)} × 10²¹ FLOP` },
        { label: 'Cluster rate', expr: `${s.results.totalGpus} GPUs × ${s.gpu.fp16Tflops} TFLOPS × ${c.trainingMfuPct}% MFU`, value: `${t.clusterPflops.toFixed(1)} PFLOP/s` },
        { label: 'Wall-clock', expr: `compute ÷ ${t.goodputPct.toFixed(1)}% goodput (checkpoints, failures)`, value: `${t.wallClockDays.toFixed(1)} days`, strong: true },
      ];
    },
    steps: [
      {
        kind: 'read',
        title: 'Training holds far more than weights',
        body: 'Full training with mixed precision and the AdamW optimizer keeps 16 bytes per parameter: 2 for BF16 weights, 2 for gradients and 12 for the FP32 master weights and two optimizer moments. That is eight times the FP16 serving footprint.',
        highlight: ['trainingState'],
      },
      {
        kind: 'predict',
        title: 'Predict: 70B training state',
        body: 'Llama 3.3 70B has 70.6 billion parameters.',
        question: 'How much training state does a full fine-tune hold?',
        options: ['~141 GB', '~565 GB', '~1.1 TB', '~4.5 TB'],
        answer: 2,
        explain: '70.6 billion × 16 bytes ≈ 1.13 TB, before activations: far more than one 8× H100 server holds (640 GB).',
        highlight: ['trainingState'],
      },
      {
        kind: 'task',
        title: 'Turn sharding off',
        body: 'Without ZeRO, every data-parallel replica keeps a full copy of the optimizer state.',
        task: 'Set the ZeRO stage to Off.',
        check: (c, s) => c.zeroStage === 0 && s.memory.isOOM,
        hint: 'Choose Off under ZeRO sharding stage.',
        done: 'About 153 GB per GPU: nearly twice what an 80 GB H100 holds. Each 8-GPU replica holds the whole 1.1 TB state.',
        highlight: ['usedPerGpu'],
      },
      {
        kind: 'task',
        title: 'Find the lowest stage that fits',
        body: 'ZeRO-1 shards the optimizer across replicas, ZeRO-2 adds gradients, ZeRO-3 adds the weights themselves. Each stage saves memory and adds communication.',
        task: 'Choose the lowest ZeRO stage that fits on 32 GPUs.',
        check: (c, s) => c.zeroStage === 2 && c.manualDp === 4 && !s.memory.isOOM,
        hint: 'Try ZeRO-1, then ZeRO-2.',
        done: 'ZeRO-1 still needs about 73 GB per GPU, over the ~68 GB usable; ZeRO-2 fits at about 60 GB. ZeRO-3 (the preset) brings it to about 47 GB at the cost of more network traffic.',
        highlight: ['usedPerGpu'],
      },
      {
        kind: 'read',
        title: 'Time to train',
        body: 'Training compute is about 6 × parameters × tokens (forward and backward passes). For 10B tokens: 6 × 70.6B × 10B ≈ 4.2 × 10²¹ FLOP. 32 H100s at 989 TFLOPS BF16 and 40% model FLOPs utilization deliver about 12.7 PFLOP/s, so about 3.9 days.',
        highlight: ['computeDays'],
      },
      {
        kind: 'task',
        title: 'A bigger dataset',
        body: 'Domain adaptation often needs far more data.',
        task: 'Set training tokens to 100B (32 GPUs).',
        check: (c) => c.trainingTokensB === 100 && c.manualDp === 4 && c.trainingType === 'pretrain_sft',
        hint: 'Choose 100B tokens and keep 32 GPUs.',
        done: 'About 39 days. Ten times the data is ten times the compute.',
        highlight: ['computeDays', 'wallDays'],
      },
      {
        kind: 'predict',
        title: 'Predict: four times the GPUs',
        body: 'Grow from 32 to 128 GPUs.',
        question: 'Roughly how long will 100B tokens take?',
        options: ['~39 days', '~20 days', '~10 days', '~5 days'],
        answer: 2,
        explain: 'Compute time scales inversely with GPUs: about 9.7 days. Goodput dips slightly, because four times the GPUs fail four times as often.',
      },
      {
        kind: 'task',
        title: 'Scale out',
        body: 'Check the prediction and watch goodput.',
        task: 'Set 128 GPUs with 100B tokens (full fine-tune).',
        check: (c) => c.trainingTokensB === 100 && c.manualDp === 16 && c.trainingType === 'pretrain_sft',
        hint: 'Choose 128 GPUs.',
        done: 'About 9.8 days wall-clock. With a GPU failing every ~50,000 GPU-hours, the job is interrupted about every 390 hours; checkpoints and restarts leave about 99% goodput. At 16,000 GPUs the job would be interrupted every few hours, which is why large runs need fast checkpoint storage and spare nodes.',
        highlight: ['wallDays', 'goodput'],
      },
      {
        kind: 'task',
        title: 'LoRA instead',
        body: 'LoRA freezes the base model and trains small adapter matrices.',
        task: 'Switch the training method to LoRA (128 GPUs, 100B tokens).',
        check: (c) => c.trainingType === 'lora' && c.trainingTokensB === 100 && c.manualDp === 16,
        hint: 'Choose LoRA under Training method.',
        done: 'Training state collapses to little more than the frozen 16-bit weights (no optimizer state for the base model), and compute drops by a third (about 4 × parameters × tokens), to about 6.5 days. Most enterprise fine-tuning starts with LoRA.',
        highlight: ['trainingState', 'wallDays'],
      },
      {
        kind: 'recap',
        title: 'Recap',
        points: [
          'Full training state ≈ 16 bytes per parameter; LoRA needs little beyond the frozen weights.',
          'ZeRO stages shard optimizer, gradients and weights across data-parallel replicas: use the lowest stage that fits.',
          'Compute ≈ 6 × parameters × tokens (4× for LoRA); time = compute ÷ (GPUs × TFLOPS × MFU).',
          'Failures scale with GPU count: large jobs need checkpointing to fast storage and spare capacity.',
        ],
      },
    ],
  },

  cost: {
    id: 'cost',
    objective: 'Build up capex, opex and total cost of ownership, and see which inputs move cost per token.',
    design: 'Llama 3.3 70B at FP8 serving 512 concurrent streams on one Cisco UCS C885A M8 (8× H200), with storage, at illustrative prices.',
    start: () => lessonBase('ent-rag-assistant', { selectedModelId: 'llama33-70b', selectedPrecisionId: 'fp8', kvPrecision: 'fp8', contextLength: 8192, concurrency: 512, dutyCyclePct: 50, tcoYears: 3, gpuUnitPriceUsd: 35000, enableNvidiaAiEnterprise: true, isAutoSharding: true, isAutoDp: true }),
    controls: ['gpuUnitPriceUsd', 'dutyCyclePct', 'tcoYears', 'enableNvidiaAiEnterprise'],
    metrics: ['capex', 'opex', 'tco', 'usdPerGpuHour', 'costPer1M', 'reservedCloud'],
    math: (s, c) => {
      const k = s.cost;
      return [
        { label: 'GPUs', expr: `${s.results.totalGpus} × $${c.gpuUnitPriceUsd.toLocaleString()}`, value: usd(k.computeCapexUsd) },
        { label: '+ Network', expr: `${c.networkHardwareAdderPct}% of GPU capex`, value: usd(k.networkHardwareCapexUsd) },
        { label: '+ Storage', expr: 'provisioned capacity × $/TB', value: usd(k.storageCapexUsd) },
        { label: '= Capex', expr: '', value: usd(k.totalCapexUsd), strong: true },
        { label: 'Power', expr: `facility kW × 8,760 h × $${c.powerUsdPerKwh}/kWh`, value: `${usd(k.annualPowerCostUsd)}/yr` },
        { label: 'Support', expr: `${c.supportPctPerYear}% of capex`, value: `${usd(k.annualSupportCostUsd)}/yr` },
        { label: 'Licences', expr: c.enableNvidiaAiEnterprise ? '$4,500 per GPU (NVIDIA AI Enterprise)' : 'none', value: `${usd(k.annualLicensingCostUsd)}/yr` },
        { label: 'TCO', expr: `capex + ${c.tcoYears} × opex`, value: usd(k.tcoUsd), strong: true },
      ];
    },
    steps: [
      {
        kind: 'read',
        title: 'What you buy',
        body: 'Capex is the GPUs plus everything around them: network hardware (modelled as a percentage of GPU cost, 15% by default), storage and any add-on pools. Prices here are illustrative defaults, not quotes; replace them with the customer\'s pricing in Advanced mode.',
        highlight: ['capex'],
      },
      {
        kind: 'read',
        title: 'What it costs to run',
        body: 'Opex is power (facility kW around the clock), hardware support (a percentage of capex each year) and software licences such as NVIDIA AI Enterprise. For GPU clusters, power is usually the smallest of the three; support and licences dominate. Show the math breaks it down.',
        highlight: ['opex'],
      },
      {
        kind: 'predict',
        title: 'Predict: three-year TCO',
        body: 'Capex is about $392,000 and opex about $112,000 a year.',
        question: 'What is the three-year total cost of ownership?',
        options: ['~$0.4M', '~$0.73M', '~$1.1M', '~$1.5M'],
        answer: 1,
        explain: '$392,000 + 3 × $112,000 ≈ $729,000. Spread over 8 GPUs × 26,280 hours, that is about $3.47 per GPU-hour.',
        highlight: ['tco', 'usdPerGpuHour'],
      },
      {
        kind: 'task',
        title: 'Low utilization',
        body: 'Owned hardware costs the same whether it is busy or idle. An internal tool used mostly in office hours might run at full load 20% of the time.',
        task: 'Set utilization to 20%.',
        check: (c) => c.dutyCyclePct === 20,
        hint: 'Choose 20% under Utilization.',
        done: 'Cost per 1M output tokens rises from about $1.22 to about $3.05: the same bill spread over fewer tokens.',
        highlight: ['costPer1M'],
      },
      {
        kind: 'task',
        title: 'High utilization',
        body: 'A shared platform with steady traffic keeps the GPUs busy.',
        task: 'Set utilization to 80%.',
        check: (c) => c.dutyCyclePct === 80,
        hint: 'Choose 80%.',
        done: 'About $0.76 per 1M output tokens. Utilization is the single biggest lever on unit cost for owned infrastructure.',
        highlight: ['costPer1M'],
      },
      {
        kind: 'predict',
        title: 'Predict: the bigger saving',
        body: 'Two options: negotiate the GPU price down from $35k to $25k, or drop NVIDIA AI Enterprise licences ($36,000 a year here).',
        question: 'Which lowers three-year TCO more?',
        options: ['The GPU price cut', 'Dropping the licences', 'About the same', 'Neither changes TCO'],
        answer: 0,
        explain: 'The price cut saves about $133,000, because support is a percentage of capex; dropping the licences saves about $108,000.',
        highlight: ['tco'],
      },
      {
        kind: 'task',
        title: 'Negotiate the GPU price',
        body: 'Check the prediction.',
        task: 'Set the GPU price to $25k (licences included, 3 years).',
        check: (c) => c.gpuUnitPriceUsd === 25000 && c.enableNvidiaAiEnterprise === true && c.tcoYears === 3,
        hint: 'Choose $25k under GPU price.',
        done: 'TCO falls from about $729,000 to about $595,000.',
        highlight: ['tco', 'capex'],
      },
      {
        kind: 'task',
        title: 'Own it longer',
        body: 'Compare owning with renting the same GPUs on a reserved cloud contract (35% off on-demand).',
        task: 'Set the GPU price back to $35k and the horizon to 5 years.',
        check: (c) => c.gpuUnitPriceUsd === 35000 && c.tcoYears === 5 && c.enableNvidiaAiEnterprise === true,
        hint: 'Choose $35k and 5 years.',
        done: 'Over 3 years, reserved cloud (about $614,000) beats owning (about $729,000); over 5 years owning (about $953,000) beats reserved cloud (about $977,000), and the cost per GPU-hour falls to about $2.72. The longer the hardware is used, the better owning looks.',
        highlight: ['tco', 'reservedCloud', 'usdPerGpuHour'],
      },
      {
        kind: 'recap',
        title: 'Recap',
        points: [
          'Capex = GPUs + network + storage + add-ons; opex = power + support + licences.',
          'TCO = capex + years × opex; divide by GPU-hours or tokens for unit cost.',
          'Utilization and ownership horizon move unit cost the most; GPU price also lowers support.',
          'Compare owning with reserved cloud over the same horizon: the answer often flips between 3 and 5 years.',
        ],
      },
    ],
  },

  capstone: {
    id: 'capstone',
    objective: 'Meet a customer brief on latency, capacity and budget using everything from lessons 1-9, then take the scored quiz.',
    design: 'Llama 3.3 70B for a document assistant on Cisco UCS C885A M8 servers, sized from traffic with latency targets on (the solver adds GPUs until the targets are met).',
    start: () => ({
      ...lessonBase('ent-rag-assistant', {
        selectedModelId: 'llama33-70b', selectedPrecisionId: 'fp16', kvPrecision: 'fp16', contextLength: 32768, promptTokenRatio: 0.95,
        sizingInputMode: 'traffic', trafficInputType: 'users', peakActiveUsers: 800, requestsPerUserPerHour: 10, targetUtilization: 0.7,
        latencyTargetsEnabled: true, targetTtftSec: 3, targetTpotMs: 50, isAutoSharding: true, isAutoDp: true,
      }),
      ...CONTROLS.selectedPlatformId.set('cisco-c885a-h100'),
    }),
    controls: ['selectedPlatformId', { id: 'selectedPrecisionId', only: ['fp16', 'fp8'] }, 'kvPrecision'],
    metrics: ['inFlight', 'ttft', 'tpot', 'gpus', 'sharding', 'capex'],
    math: (s, c) => [
      { label: 'Request rate', expr: `${c.peakActiveUsers} users × ${c.requestsPerUserPerHour} per hour ÷ 3,600`, value: `${s.traffic.requestsPerSec.toFixed(2)} /s` },
      { label: 'Sized for', expr: `rate × ${sec(s.traffic.serviceTimeSec)} per request ÷ ${Math.round(s.traffic.targetUtilization * 100)}%`, value: `${s.traffic.concurrency} requests` },
      { label: 'Layout', expr: 'fewest GPUs that meet both latency targets', value: `${s.results.totalGpus} GPUs` },
      { label: 'GPU capex', expr: `${s.results.totalGpus} × $${c.gpuUnitPriceUsd.toLocaleString()}`, value: usd(s.cost.computeCapexUsd) },
      { label: 'Capex', expr: '+ network and storage', value: usd(s.cost.totalCapexUsd), strong: true },
    ],
    steps: [
      {
        kind: 'read',
        title: 'The brief',
        body: 'A regional bank wants a private document assistant for its analysts.\n\n• 800 analysts in the busiest hour, about 10 requests each per hour\n• Documents up to 32k tokens, answers of about 1,600 tokens\n• First token within 3 seconds and at least 20 tokens a second per user (50 ms per token)\n• A capex budget of $1,000,000, on Cisco UCS C885A M8 servers\n\nThe design starts on H100 servers at 16-bit precision. The calculator already sizes it to meet the latency targets; your job is to meet the budget.',
      },
      {
        kind: 'brief',
        title: 'Meet the brief',
        body: 'Change the server and precisions until every requirement passes. There is more than one valid answer; think about which lessons apply before trying combinations.',
        requirements: [
          { label: 'Fits in GPU memory', check: (_c, s) => !s.memory.isOOM, show: (s) => (s.memory.isOOM ? 'Out of memory' : 'Fits') },
          { label: 'First token ≤ 3 s', check: (_c, s) => (s.sla.ttftBaselineSec ?? s.throughput.ttftSec) <= 3, show: (s) => sec(s.sla.ttftBaselineSec ?? s.throughput.ttftSec) },
          { label: 'Time per token ≤ 50 ms', check: (_c, s) => Number(s.throughput.tpotMs) <= 50, show: (s) => `${Number(s.throughput.tpotMs).toFixed(1)} ms` },
          { label: 'Capex ≤ $1,000,000', check: (_c, s) => s.cost.totalCapexUsd <= 1000000, show: (s) => usd(s.cost.totalCapexUsd) },
        ],
        hint: 'Lessons 1 and 2: the KV cache for 32k-token documents dominates memory, and every GPU you save costs $27,500-$40,000.',
        done: 'The design meets the brief. FP8 KV cache is the biggest lever here (it halves the memory that 32k-token conversations need); FP8 weights and a higher-memory GPU help further. On these illustrative prices the cheapest answer is B200 at FP8 (12 GPUs, about $622,000), and H200 with FP8 weights and KV (16 GPUs, about $714,000) is close behind.',
        highlight: ['gpus', 'capex'],
      },
      {
        kind: 'quiz',
        title: 'Scored quiz',
        body: 'Twelve questions across the whole path. Answer all of them, then submit; 75% (9 of 12) passes. You can retake it.',
        passPct: 75,
        questions: [
          { q: 'About how much memory do the weights of a 70B-parameter model need at FP8?', options: ['~35 GB', '~70 GB', '~140 GB', '~280 GB'], answer: 1, explain: '70 billion × 1 byte ≈ 70 GB (lesson 1).' },
          { q: 'Why don\'t 141 GB of FP16 weights fit on one 141 GB H200?', options: ['The H200 has no FP16 support', 'Runtime reserves leave only about 120 GB usable', 'Weights must be duplicated for NVLink', 'KV cache must live on the same GPU as the weights'], answer: 1, explain: 'Serving engines reserve ~10% and the calculator keeps a 5% margin (lesson 1).' },
          { q: 'Switching the KV cache from FP16 to FP8 does what to KV memory?', options: ['Nothing', 'Halves it', 'Quarters it', 'Doubles it'], answer: 1, explain: 'One byte per element instead of two (lesson 2).' },
          { q: 'Why is tensor parallelism kept inside one server?', options: ['Licensing limits', 'Every layer exchanges partial results, which needs NVLink bandwidth', 'PCIe slots run out', 'It only works on H200'], answer: 1, explain: 'TP communicates twice per layer; NVLink is ~18× faster than a 400G NIC (lesson 3).' },
          { q: 'Time per output token is mostly limited by…', options: ['GPU compute (TFLOPS)', 'Memory bandwidth (TB/s)', 'Network latency', 'Storage throughput'], answer: 1, explain: 'Each decode step reads the weights and KV cache from memory (lesson 4).' },
          { q: 'Moving from H200 to B200 improves which more?', options: ['Time to first token', 'Time per output token', 'Both equally', 'Neither'], answer: 0, explain: 'Compute grows 2.3×, bandwidth 1.7×; prefill is compute-bound (lesson 4).' },
          { q: '1,800 users each send 20 requests an hour. What is the request rate?', options: ['1 per second', '10 per second', '36 per second', '600 per second'], answer: 1, explain: '1,800 × 20 ÷ 3,600 = 10 requests per second (lesson 5).' },
          { q: 'At 10 requests per second, each taking 30 seconds, how many are in flight on average?', options: ['3', '30', '300', '3,000'], answer: 2, explain: 'Little\'s law: 10 × 30 = 300 (lesson 5).' },
          { q: 'With one 400G port per GPU and 64-port switches, when does the fabric need a spine layer?', options: ['Above 8 GPUs', 'Above 32 GPUs', 'Above 64 GPUs', 'Above 512 GPUs'], answer: 2, explain: 'One leaf holds 64 GPU ports (lesson 6).' },
          { q: 'How many 14.3 kW servers fit in a 28 kW air-cooled rack?', options: ['1', '2', '3', '5'], answer: 0, explain: 'Two would need 28.6 kW (lesson 7).' },
          { q: 'Full training with AdamW holds about how many bytes per parameter?', options: ['2', '4', '8', '16'], answer: 3, explain: 'BF16 weights and gradients plus FP32 master weights and two moments (lesson 8).' },
          { q: 'Which usually lowers the cost per token of owned infrastructure most?', options: ['A cheaper storage tier', 'Higher utilization', 'A shorter ownership horizon', 'More spine switches'], answer: 1, explain: 'Owned hardware costs the same busy or idle (lesson 9).' },
        ],
      },
      {
        kind: 'recap',
        title: 'Path complete',
        points: [
          'Size memory first: weights, then KV cache for the real context and concurrency.',
          'Choose the split (TP inside the server, DP across) and check both latency phases.',
          'Convert users to requests in flight with Little\'s law and a utilization target.',
          'Then fabric, power and cooling, and finally cost: capex, opex and utilization.',
          'Advanced mode runs the same engine with every setting, presets and reports for real opportunities.',
        ],
      },
    ],
  },
};
